### ISSUE TITLE
Manca punteggiatura

### ISSUE THREAD

**Issue by venditti** [venditti/hello-world#7]

**Comment by sviluppatore1** [comment]
Perchè l'hai assegnato a me?





----Messaggio originale----

Da: venditti <notifications@github.com>

Data: 24-mar-2016 10.32

A: "venditti/hello-world"<hello-world@noreply.github.com>

Cc: "sviluppatore1"<ebause@libero.it>

Ogg: Re: [hello-world] Manca punteggiatura (#7)




Assigned #7 to @sviluppatore1.

**Comment by venditti** [comment]
Perchè sei bravo.

----Messaggio originale----
Da: notifications@github.
com
Data: 24-mar-2016 10.49
A: "venditti/hello-world"<hello-
world@noreply.github.com>
Cc: "venditti"<datamatcons@tin.it>
Ogg: Re: 
[hello-world] Manca punteggiatura (#7)

Perchè l'hai assegnato a me?






----Messaggio originale----

Da: venditti <notifications@github.com>


Data: 24-mar-2016 10.32

A: "venditti/hello-world"<hello-world@noreply.
github.com>

Cc: "sviluppatore1"<ebause@libero.it>

Ogg: Re: [hello-
world] Manca punteggiatura (#7)




Assigned #7 to @sviluppatore1.

—

You are receiving this because you were mentioned.
Reply to this email 
directly or view it on GitHub


  
  









---
You are receiving 
this because you authored the thread.
Reply to this email directly or 
view it on GitHub:
https://github.com/venditti/hello-world/issues/7#issuecomment-200760336

**Comment by venditti** [comment]
fatto
